name: Maven  CICD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:  
  USERNAME: ${{secrets.DOCKER_USERNAME}}
  PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '11'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2


      - name: Maven Build and Test 
        run: mvn -B package --file pom.xml

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
        
      # - name: Maven Build  
      #   run: docker build -t anuragsingh2207/hello-world-django:latest .

      # - name: Docker Login
      #   run: docker login -u="${{env.USERNAME}}" -p="${{env.PASSWORD}}"

      # - name: Push Docker Image
      #   run: docker push  anuragsingh2207/hello-world-django:latest